#!/bin/sh
SOC=`grep Hardware /proc/cpuinfo | cut -d' ' -f 2`
if [ "$SOC" = BCM2835 ];then
    exec sudo openocd-esp32 -f cfg/esp32-raspi1.cfg
else
    exec sudo openocd-esp32 -f cfg/esp32-raspi2.cfg
fi
