#!/bin/sh
if grep 'ARMv6' /proc/cpuinfo > /dev/null;then
    IF=interface/raspberrypi-native.cfg
else
    IF=interface/raspberrypi2-native.cfg
fi

exec sudo openocd-esp32 -f $IF -f cfg/esp32-raspi.cfg
