#!/bin/sh
./reset download
python ~/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/ttyAMA0 --baud 115200 --before no_reset --after no_reset erase_region 0xd000 0x20000
./reset
