#!/bin/sh
if [ $# -lt 2 ];then
    echo usage: writeflash ADDR IMAGE [ADDR IMAGE]... >&2
    exit 1
fi

./reset download
esptool.py --chip esp32 --port /dev/ttyAMA0 --baud 115200 write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect $*
./reset
