COMPONENT_OWNBUILDTARGET	:= build
COMPONENT_OWNCLEANTARGET 	:= clean
COMPONENT_ADD_INCLUDEDIRS        = .

MAKEPARAM			:= BUILD_DIR_BASE=$(BUILD_DIR_BASE) \
				   COMPONENT_BUILD_DIR=$(COMPONENT_BUILD_DIR) \
				   COMPONENT_PATH=$(COMPONENT_PATH)

build:
	make -C$(COMPONENT_PATH) $(MAKEPARAM) build

clean:
	make -C$(COMPONENT_PATH) $(MAKEPARAM) clean
